// app/api/verbatim/resumes/route.ts
//
// The owner's résumé-version library: list, create, upload a file, rename, choose which one is
// public, delete.
//
// ⚠️ EVERY DB HANDLER USES THE CALLER'S OWN SESSION, NEVER THE SERVICE ROLE — the same rule as
// app/api/jobs/postings, for the same reason: a version's label names the company it was tailored
// for, so RLS must be the guarantee rather than a `.eq('owner_id', …)` a refactor can drop. There
// is no admin path here at all.
//
// ⚠️ The one service-role use is the STORAGE write, and it is safe only because the path is
// computed from `gate.user.id` — the client sends bytes and a format, never a name. See
// `storagePathFor`.

import { NextResponse } from 'next/server';
import { getServerSupabase } from '@/lib/supabase/server';
import { supabaseAdmin } from '@/lib/supabase/admin';
import { requireUser } from '@/lib/auth/requireUser';
import {
  RESUME_BUCKET,
  RESUME_FORMATS,
  createVersion,
  deleteVersion,
  isResumeFormat,
  listVersions,
  setPublicVersion,
  storagePathFor,
  updateVersion,
  type ResumeFile,
  type ResumeVersion,
} from '@/lib/resumes/versions';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

const MAX_BYTES = 10 * 1024 * 1024;

export async function GET() {
  const gate = await requireUser();
  if (gate instanceof NextResponse) return gate;
  const db = await getServerSupabase();
  return NextResponse.json({ versions: await listVersions(db) });
}

/**
 * Two shapes, one route:
 *   • JSON  { label, notes }            → create an empty version
 *   • multipart { versionId, format, file } → attach a file to one
 */
export async function POST(req: Request) {
  const gate = await requireUser();
  if (gate instanceof NextResponse) return gate;
  const db = await getServerSupabase();

  const ct = req.headers.get('content-type') ?? '';
  if (!ct.includes('multipart/form-data')) {
    const body = await req.json().catch(() => ({}));
    const { version, error } = await createVersion(db, gate.user.id, body ?? {});
    if (error) return NextResponse.json({ error }, { status: 400 });
    return NextResponse.json({ version });
  }

  const form = await req.formData().catch(() => null);
  if (!form) return NextResponse.json({ error: 'Could not read the upload.' }, { status: 400 });

  const versionId = String(form.get('versionId') ?? '');
  const format = String(form.get('format') ?? '');
  const file = form.get('file');
  if (!versionId) return NextResponse.json({ error: 'versionId is required' }, { status: 400 });
  if (!isResumeFormat(format)) {
    return NextResponse.json({ error: 'Format must be pdf, docx or md.' }, { status: 400 });
  }
  if (!(file instanceof File) || file.size === 0) {
    return NextResponse.json({ error: 'Attach a file.' }, { status: 400 });
  }
  if (file.size > MAX_BYTES) {
    return NextResponse.json({ error: 'That file is over 10 MB.' }, { status: 400 });
  }

  // Read the row through the CALLER's client: if it is not theirs, RLS returns nothing and we stop
  // here — before any service-role storage write happens.
  //
  // ⚠️ `as any`: `resume_versions` is not in types/supabase.ts, which is regenerated by hand and
  // documented as lagging (CLAUDE.md §8 — it needs Docker or an access token). The repo's usual
  // answer is "use the untyped service-role client", which is precisely what this table must NOT
  // use. Losing the generated types is the cheaper trade than losing RLS. Same call as
  // app/verbatim/workspace/page.tsx.
  const anyDb = db as any;
  const { data: owned } = await anyDb
    .from('resume_versions')
    .select('id, files')
    .eq('id', versionId)
    .maybeSingle();
  if (!owned) return NextResponse.json({ error: 'No such version.' }, { status: 404 });

  const path = storagePathFor(gate.user.id, versionId, format);
  const bytes = new Uint8Array(await file.arrayBuffer());
  const up = await supabaseAdmin.storage.from(RESUME_BUCKET).upload(path, bytes, {
    contentType: RESUME_FORMATS[format].contentType,
    upsert: true,
  });
  if (up.error) return NextResponse.json({ error: up.error.message }, { status: 400 });

  const next: ResumeFile[] = [
    ...(((owned as { files?: ResumeFile[] }).files ?? []) as ResumeFile[]).filter(
      (f) => f.format !== format
    ),
    { format, path, size_bytes: file.size, content_type: RESUME_FORMATS[format].contentType },
  ];

  const { data: saved, error } = await anyDb
    .from('resume_versions')
    .update({ files: next, updated_at: new Date().toISOString() })
    .eq('id', versionId)
    .select('*')
    .maybeSingle();
  if (error) return NextResponse.json({ error: error.message }, { status: 400 });

  return NextResponse.json({ version: saved as ResumeVersion });
}

export async function PATCH(req: Request) {
  const gate = await requireUser();
  if (gate instanceof NextResponse) return gate;
  const body = await req.json().catch(() => ({}));
  const db = await getServerSupabase();

  // `{ publicId: <id> | null, siteId }` — choose what one site serves, or take it down.
  //
  // ⚠️ `siteId` is required to publish and is NOT optional-with-a-fallback. The tempting fallback
  // ("use the owner's site") is the leak fixed in migration 20260830 — an owner here may have
  // thousands of client sites, and every one of them served the résumé.
  if ('publicId' in (body ?? {})) {
    const id = body.publicId === null ? null : String(body.publicId ?? '');
    const siteId = typeof body?.siteId === 'string' ? body.siteId : null;
    const err = await setPublicVersion(db, id || null, siteId);
    if (err) return NextResponse.json({ error: err }, { status: 400 });
    return NextResponse.json({ ok: true });
  }

  const id = typeof body?.id === 'string' ? body.id : '';
  if (!id) return NextResponse.json({ error: 'id is required' }, { status: 400 });
  // No hand-rolled ownership check: RLS scopes the UPDATE, so someone else's id matches no row.
  const err = await updateVersion(db, id, body ?? {});
  if (err) return NextResponse.json({ error: err }, { status: 400 });
  return NextResponse.json({ ok: true });
}

export async function DELETE(req: Request) {
  const gate = await requireUser();
  if (gate instanceof NextResponse) return gate;
  const id = new URL(req.url).searchParams.get('id') ?? '';
  if (!id) return NextResponse.json({ error: 'id is required' }, { status: 400 });
  const db = await getServerSupabase();

  // Read the paths through the caller's client first — both to confirm ownership via RLS and to
  // know what to remove. ⚠️ Storage is cleaned BEFORE the row is deleted: if the row went first,
  // the paths would be unknowable and the objects would live on in the bucket forever. A résumé
  // someone deleted is exactly the file that must not quietly survive.
  const { data: row } = await (db as any)
    .from('resume_versions')
    .select('files')
    .eq('id', id)
    .maybeSingle();
  if (!row) return NextResponse.json({ error: 'No such version.' }, { status: 404 });

  const paths = (((row as { files?: ResumeFile[] }).files ?? []) as ResumeFile[])
    .map((f) => f.path)
    .filter(Boolean);
  if (paths.length) await supabaseAdmin.storage.from(RESUME_BUCKET).remove(paths);

  const err = await deleteVersion(db, id);
  if (err) return NextResponse.json({ error: err }, { status: 400 });
  return NextResponse.json({ ok: true });
}
