// lib/outreach/contractorFlyer.ts
//
// A printable one-page flyer for a local contractor, with a QR to their site.
//
// ⚠️ THIS IS THE OTHER HALF OF A REAL ACQUISITION LOOP, AND THE HONEST ONE. A contractor hands
// out flyers; we turn the flyer into a site; we hand back a better flyer that points at it. The
// value is legible before anyone signs up for anything — which is the shape the mesh concluded
// actually works (crosstalk 2026-08-05: give something useful whether or not they ever convert).
//
// ⚠️ IT REPEATS ONLY WHAT THEY CLAIM. No "licensed", no "insured", no "family owned", no years in
// business, no review count — none of that is ours to add, and a flyer is exactly where an
// invented credential would do real damage, because it goes to THEIR customers under THEIR name.
// The input type has no field for any of it, which is the enforcement.
//
// ⚠️ NO OUR-BRANDING ON IT. It is a document they hand to their customers; a "made with" badge
// would be us advertising through their business. Same rule as the Verbatim résumé export.
// Attribution belongs in the message we send them, not on the artefact.
//
// ⚠️ NO PEOPLE AND NO PHOTOS WE DID NOT MAKE. Rule 9 (lib/images/noPeople.ts) plus the plain fact
// that a flyer's stock before/after images are not ours to republish.

export type ContractorFlyer = {
  businessName: string;
  /** One line, in their words. */
  tagline?: string | null;
  /** Exactly the services they list. */
  services: string[];
  /** e.g. "Two year guarantee" — only if they say it. */
  guarantee?: string | null;
  phone: string;
  /** tel: href — digits only, e.g. "+12099615328". */
  phoneHref: string;
  siteUrl: string;
  /** data: URI PNG. Generated by the caller so this module stays pure. */
  qrDataUri: string;
  /** Their own closing line, if they have one ("We can negotiate."). */
  closingNote?: string | null;
  /** Keep their write-in quote line — it is why door-to-door flyers work. */
  quoteLine?: boolean;
  /**
   * Optional trade image, as a data URI.
   *
   * ⚠️ DECORATIVE ONLY — NEVER A BEFORE/AFTER. A generic image of the work illustrates the trade
   * and claims nothing. A before/after pair is a CLAIM ("we produced this result"), and a
   * generated one is a fabricated portfolio on a real contractor's advertising — the same class
   * as an invented testimonial. If they want before/afters, they must be photographs of their own
   * jobs, supplied by them.
   */
  imageDataUri?: string | null;
};

function esc(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

/**
 * Letter portrait, printed at 100%. Deliberately high-contrast black on white: this gets
 * photocopied, left on a porch in the rain, and read at arm's length from a doorway.
 */
export function renderContractorFlyerHtml(f: ContractorFlyer): string {
  const services = f.services
    .map((s) => `<li>${esc(s)}</li>`)
    .join('\n');

  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><title>${esc(f.businessName)}</title>
<style>
  :root { color-scheme: only light; }
  @page { size: Letter; margin: 0; }
  * { box-sizing: border-box; }
  body { margin: 0; width: 8.5in; height: 11in; padding: 0.55in 0.7in;
         font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; color: #000; background: #fff;
         display: flex; flex-direction: column;
         /* ⚠️ ONE PAGE, GUARANTEED. A flyer that silently becomes two pages wastes half of every
            print run and nobody notices until the paper comes out. The sizes above are tuned to
            fit; this is the backstop. The generator asserts the page count as well, because
            clipping and fitting look identical in a PDF viewer. */
         overflow: hidden; }

  h1 { font-size: 50pt; line-height: .95; margin: 0; letter-spacing: -.02em; text-transform: uppercase; }
  .rule { height: 6pt; background: #000; margin: 14pt 0 0; }
  .tagline { font-size: 15pt; margin: 10pt 0 0; }

  .services { margin: 20pt 0 0; padding: 0; list-style: none;
              display: grid; grid-template-columns: 1fr 1fr; gap: 11pt 20pt; }
  .services li { font-size: 18pt; font-weight: 600; padding-left: 22pt; position: relative; }
  /* A drawn check, not an emoji or an image — prints black on any printer. */
  .services li::before { content: ""; position: absolute; left: 0; top: 6pt;
      width: 7pt; height: 14pt; border: solid #000; border-width: 0 3pt 3pt 0; transform: rotate(45deg); }

  .guarantee { margin: 20pt 0 0; display: inline-block; border: 3pt solid #000;
               padding: 7pt 14pt; font-size: 16pt; font-weight: 800; text-transform: uppercase; }

  .spacer { flex: 1 1 auto; min-height: 8pt; }
  /* Decorative band. alt="" on purpose — it illustrates, it does not inform. */
  .art { margin: 18pt 0 0; }
  .art img { width: 100%; height: 1.9in; object-fit: cover; display: block; border: 2pt solid #000; }

  .callbar { border-top: 3pt solid #000; padding-top: 16pt; display: flex; align-items: center; gap: 22pt; }
  .callbar .num { font-size: 40pt; font-weight: 800; letter-spacing: -.02em; line-height: 1; }
  .callbar .label { font-size: 12pt; text-transform: uppercase; letter-spacing: .1em; margin-bottom: 4pt; }
  .qr { text-align: center; }
  .qr img { width: 1.5in; height: 1.5in; display: block; }
  .qr span { font-size: 9.5pt; display: block; margin-top: 4pt; max-width: 1.5in; line-height: 1.25; }

  .foot { margin-top: 14pt; display: flex; justify-content: space-between; align-items: flex-end; gap: 20pt; }
  .quote { font-size: 15pt; }
  .quote b { font-weight: 800; }
  .note { font-size: 13pt; font-style: italic; }
  .url { font-size: 11pt; margin-top: 6pt; word-break: break-all; }
</style></head><body>

  <h1>${esc(f.businessName)}</h1>
  <div class="rule"></div>
  ${f.tagline ? `<p class="tagline">${esc(f.tagline)}</p>` : ''}

  <ul class="services">
${services}
  </ul>

  ${f.guarantee ? `<div class="guarantee">${esc(f.guarantee)}</div>` : ''}

  ${f.imageDataUri ? `<div class="art"><img src="${f.imageDataUri}" alt=""></div>` : ''}

  <div class="spacer"></div>

  <div class="callbar">
    <div>
      <div class="label">Call for a free quote</div>
      <div class="num">${esc(f.phone)}</div>
      <div class="url">${esc(f.siteUrl.replace(/^https?:\/\//, '').replace(/\/$/, ''))}</div>
    </div>
    <div class="qr">
      <img src="${f.qrDataUri}" alt="Scan for services and a free quote">
      <span>Scan to see services &amp; request a quote</span>
    </div>
  </div>

  <div class="foot">
    ${f.quoteLine ? `<div class="quote">Your quote <b>$__________</b></div>` : '<div></div>'}
    ${f.closingNote ? `<div class="note">${esc(f.closingNote)}</div>` : ''}
  </div>

</body></html>`;
}
