// lib/outreach/contractorSignPack.ts
//
// The yard-sign pack for a trade contractor: the sign that goes in a customer's lawn while the
// work is happening, and the cards that go in a neighbour's hand afterwards.
//
// ⚠️ WHY THIS IS THE STRONGEST ASSET WE MAKE FOR A TRADE. A freshly sealed driveway is visible
// from six other houses, and every one of them is deciding whether theirs looks tired. The sign
// converts an already-completed job into the cheapest possible lead, and the QR is what turns
// "who did that?" into a phone number without anyone writing anything down. Sibling of
// lib/listings/qrPack.ts, which does the same job for a realtor's listing.
//
// ⚠️ THE SIGN MAKES A CLAIM ABOUT A SPECIFIC PROPERTY, AND THAT IS NOT DECORATION. "This driveway
// was sealed by X" asserts that X did this work, at this address. Two consequences the generated
// instructions state plainly, because a contractor putting our artefact in a stranger's lawn is
// carrying the risk:
//   1. It goes up only where the work was actually done by them.
//   2. It needs the homeowner's permission — a sign in someone's yard is their yard, not ours,
//      and "everyone does it" is not consent.
// We cannot enforce either. We can refuse to pretend they don't apply.

export type SignVariant = 'in_progress' | 'completed';

export type ContractorSignPack = {
  businessName: string;
  /** The trade word as it appears on the sign: "sealed", "paved", "roofed", "landscaped". */
  workVerb: string;
  phone: string;
  siteUrl: string;
  /** data: URI PNG, generated by the caller so this module stays pure. */
  qrDataUri: string;
  variant: SignVariant;
};

function esc(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function headline(p: ContractorSignPack): string {
  return p.variant === 'in_progress'
    ? `WORK IN PROGRESS BY`
    : `THIS DRIVEWAY WAS ${p.workVerb.toUpperCase()} BY`;
}

/**
 * 18×24in portrait — the standard corrugated-plastic yard sign, at true size so a print shop can
 * take the PDF straight. Everything is enormous on purpose: this is read from a moving car.
 */
export function renderYardSignHtml(p: ContractorSignPack): string {
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><title>${esc(p.businessName)} — yard sign</title>
<style>
  :root { color-scheme: only light; }
  @page { size: 18in 24in; margin: 0; }
  * { box-sizing: border-box; }
  body { margin: 0; width: 18in; height: 24in; padding: 1.1in 1in;
         font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; color: #000; background: #fff;
         display: flex; flex-direction: column; text-align: center; overflow: hidden; }
  .kicker { font-size: 46pt; font-weight: 700; letter-spacing: .02em; line-height: 1.1; }
  h1 { font-size: 150pt; line-height: .88; margin: .28in 0 0; letter-spacing: -.03em; text-transform: uppercase; }
  .rule { height: 18pt; background: #000; margin: .45in 0; }
  .phone { font-size: 108pt; font-weight: 800; letter-spacing: -.02em; line-height: 1; }
  .spacer { flex: 1 1 auto; }
  .qrRow { display: flex; align-items: center; justify-content: center; gap: .6in; }
  .qrRow img { width: 5.6in; height: 5.6in; display: block; }
  .qrRow .say { font-size: 40pt; font-weight: 700; text-align: left; line-height: 1.15; max-width: 6.4in; }
  .url { font-size: 30pt; margin-top: .3in; }
</style></head><body>
  <div class="kicker">${esc(headline(p))}</div>
  <h1>${esc(p.businessName)}</h1>
  <div class="rule"></div>
  <div class="phone">${esc(p.phone)}</div>
  <div class="spacer"></div>
  <div class="qrRow">
    <img src="${p.qrDataUri}" alt="">
    <div class="say">Scan for a<br>free quote</div>
  </div>
  <div class="url">${esc(p.siteUrl.replace(/^https?:\/\//, '').replace(/\/$/, ''))}</div>
</body></html>`;
}

/**
 * 10 business cards, 3.5×2in, on one letter sheet with cut guides.
 *
 * ⚠️ Cards are the half of this pack that gets used every day. A contractor knocking on the two
 * neighbouring doors after a job needs something to leave behind, and a card that scans to their
 * own site beats a phone number written on a torn flyer corner.
 */
export function renderBusinessCardsHtml(p: ContractorSignPack): string {
  const card = `
    <div class="card">
      <div class="name">${esc(p.businessName)}</div>
      <div class="phone">${esc(p.phone)}</div>
      <img class="qr" src="${p.qrDataUri}" alt="">
      <div class="url">${esc(p.siteUrl.replace(/^https?:\/\//, '').replace(/\/$/, ''))}</div>
    </div>`;

  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><title>${esc(p.businessName)} — cards</title>
<style>
  :root { color-scheme: only light; }
  @page { size: Letter; margin: 0; }
  * { box-sizing: border-box; }
  body { margin: 0; width: 8.5in; height: 11in; padding: .5in .75in;
         font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; color: #000; background: #fff;
         display: grid; grid-template-columns: 3.5in 3.5in; grid-auto-rows: 2in;
         gap: 0; justify-content: center; overflow: hidden; }
  .card { border: .5pt dashed #999; padding: .16in .18in; position: relative;
          display: flex; flex-direction: column; justify-content: center; }
  .name { font-size: 13pt; font-weight: 800; line-height: 1.05; text-transform: uppercase; max-width: 2.2in; }
  .phone { font-size: 15pt; font-weight: 800; margin-top: .06in; }
  .url { font-size: 7pt; color: #333; margin-top: .05in; max-width: 2.2in; }
  .qr { position: absolute; right: .16in; top: 50%; transform: translateY(-50%); width: .95in; height: .95in; }
</style></head><body>
${card.repeat(10)}
</body></html>`;
}

/**
 * The page the contractor reads before printing anything.
 *
 * ⚠️ It is a separate sheet, NOT text on the sign. Instructions on the sign would be read by the
 * neighbours it is aimed at; instructions on their own page are read by the person who needs them.
 */
export function renderSignInstructionsHtml(p: ContractorSignPack): string {
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><title>How to use these</title>
<style>
  :root { color-scheme: only light; }
  @page { size: Letter; margin: .8in; }
  body { font: 12pt/1.55 "Helvetica Neue", Helvetica, Arial, sans-serif; color: #111; max-width: 6.6in; }
  h1 { font-size: 20pt; margin: 0 0 .2in; }
  h2 { font-size: 12pt; text-transform: uppercase; letter-spacing: .08em; color: #555; margin: .3in 0 .08in; }
  li { margin-bottom: .09in; }
  .warn { border-left: 3pt solid #000; padding: .1in .2in; background: #f4f4f4; margin-top: .28in; }
</style></head><body>
  <h1>Your signs and cards</h1>

  <h2>Yard sign — 18 × 24 inches</h2>
  <p>Any sign shop can print the PDF on corrugated plastic with an H-stake. Ask for
  &ldquo;18 by 24 coroplast, single sided&rdquo;. It is designed to be read from a passing car.</p>

  <h2>Business cards — 10 per sheet</h2>
  <p>Print on card stock and cut along the dashed lines, or send the PDF to any print shop. The
  code goes straight to your site, so a neighbour can see your work and call you without writing
  anything down.</p>

  <div class="warn">
    <strong>Two things before a sign goes in a yard.</strong>
    <ul>
      <li><strong>Ask the homeowner first.</strong> It is their property. Most people say yes if
      you ask while you are finishing up — some will say no, and that has to be fine.</li>
      <li><strong>Only where you did the work.</strong> The sign says this job is yours. That has
      to be true of the driveway it is standing on.</li>
    </ul>
  </div>
</body></html>`;
}
