// app/verbatim/workspace/page.tsx
//
// The Verbatim job-seeker workspace: your résumé sites and the postings you are pursuing.
//
// ⚠️ SIGNED-IN ONLY, AND NEVER PART OF A PUBLISHED SITE. The résumé page a Verbatim user publishes
// is public by design; this is the opposite — a private list of who they are applying to. Nothing
// here is reachable from a tenant render, and there is no shareable URL for someone else's board.
import { redirect } from 'next/navigation';
import { getServerSupabase } from '@/lib/supabase/server';
import WorkspaceClient from './workspace-client';

export const dynamic = 'force-dynamic';

export const metadata = {
  title: 'Your job search — Verbatim',
  // A private board must never be indexed, even behind auth: a crawler that ever sees it once
  // (a shared session, a misconfigured proxy) would publish the fact of the search itself.
  robots: { index: false, follow: false },
};

export default async function VerbatimWorkspacePage() {
  const db = await getServerSupabase();
  const { data: { user } } = await db.auth.getUser();
  if (!user) redirect('/login?next=/verbatim/workspace');

  // Both queries run as the USER, so RLS scopes them. See lib/jobs/postings.ts.
  //
  // ⚠️ Cast to `any`: `job_postings` is not in types/supabase.ts, which is regenerated by hand and
  // documented as lagging (CLAUDE.md §8 — it needs Docker or an access token, neither available in
  // a headless session). The repo's usual answer is "use the untyped service-role client", which
  // is exactly what this table must NOT use. Losing the generated types is the cheaper trade than
  // losing RLS.
  const anyDb = db as any;
  const [{ data: postings }, { data: sites }] = await Promise.all([
    anyDb.from('job_postings').select('*').order('created_at', { ascending: false }).limit(200),
    anyDb
      .from('templates')
      .select('id, slug, data, published')
      .eq('owner_id', user.id)
      .order('created_at', { ascending: false })
      .limit(50),
  ]);

  const resumeSites = (sites ?? [])
    .filter((t: any) => ['personal', 'author'].includes(t?.data?.meta?.industry))
    .map((t: any) => ({
      id: t.id,
      slug: t.slug,
      name: t?.data?.meta?.business_name ?? t?.data?.meta?.siteTitle ?? t.slug,
      published: !!t.published,
    }));

  return <WorkspaceClient postings={(postings as any[]) ?? []} resumeSites={resumeSites} />;
}
