// app/verbatim/workspace/page.tsx
//
// The Verbatim job-seeker workspace: your résumé sites and the postings you are pursuing.
//
// ⚠️ SIGNED-IN ONLY, AND NEVER PART OF A PUBLISHED SITE. The résumé page a Verbatim user publishes
// is public by design; this is the opposite — a private list of who they are applying to. Nothing
// here is reachable from a tenant render, and there is no shareable URL for someone else's board.
import { signInHref } from '@/lib/auth/authLinks';
import { redirect } from 'next/navigation';
import { getServerSupabase } from '@/lib/supabase/server';
import { publicSiteUrl } from '@/lib/sites/publicUrl';
import WorkspaceClient from './workspace-client';

export const dynamic = 'force-dynamic';

export const metadata = {
  title: 'Your job search — Verbatim',
  // A private board must never be indexed, even behind auth: a crawler that ever sees it once
  // (a shared session, a misconfigured proxy) would publish the fact of the search itself.
  robots: { index: false, follow: false },
};

export default async function VerbatimWorkspacePage() {
  const db = await getServerSupabase();
  const { data: { user } } = await db.auth.getUser();
  if (!user) redirect(signInHref('/verbatim/workspace'));

  // Both queries run as the USER, so RLS scopes them. See lib/jobs/postings.ts.
  //
  // ⚠️ Cast to `any`: `job_postings` is not in types/supabase.ts, which is regenerated by hand and
  // documented as lagging (CLAUDE.md §8 — it needs Docker or an access token, neither available in
  // a headless session). The repo's usual answer is "use the untyped service-role client", which
  // is exactly what this table must NOT use. Losing the generated types is the cheaper trade than
  // losing RLS.
  const anyDb = db as any;
  const [{ data: postings }, { data: sites }, { data: versions }] = await Promise.all([
    anyDb.from('job_postings').select('*').order('created_at', { ascending: false }).limit(200),
    anyDb
      .from('templates')
      .select('id, slug, data, published, custom_domain, default_subdomain')
      .eq('owner_id', user.id)
      .order('created_at', { ascending: false })
      .limit(50),
    anyDb
      .from('resume_versions')
      .select('*')
      .order('created_at', { ascending: false })
      .limit(100),
  ]);

  const allVersions = (versions as any[]) ?? [];

  const resumeSites = (sites ?? [])
    .filter((t: any) => ['personal', 'author'].includes(t?.data?.meta?.industry))
    .map((t: any) => ({
      id: t.id,
      slug: t.slug,
      name: t?.data?.meta?.business_name ?? t?.data?.meta?.siteTitle ?? t.slug,
      published: !!t.published,
      url: publicSiteUrl(t),
      // Which version this site actually serves. Resolved per SITE, never per owner — see
      // migration 20260830; an owner here may have thousands of sites.
      servingLabel:
        allVersions.find((v) => v.is_public && v.public_site_id === t.id)?.label ?? null,
    }));

  // Which site the public résumé link belongs to. ⚠️ The first PUBLISHED one, not simply the
  // first: an unpublished draft has no audience, so offering to "make a résumé public" on it would
  // describe a reach the site does not have.
  const publicSite = resumeSites.find((s: { published: boolean }) => s.published) ?? null;

  return (
    <WorkspaceClient
      postings={(postings as any[]) ?? []}
      resumeSites={resumeSites}
      versions={allVersions}
      siteSlug={publicSite?.slug ?? null}
      siteId={publicSite?.id ?? null}
    />
  );
}
