---
name: Bug report
about: Report a bug or unexpected behavior
title: "[BUG] "
labels: ["bug"]
assignees: []

---

**Describe the bug**
A clear and concise description of the problem.

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
What you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain.

**Device / OS / Browser**

**Additional context**
Add any other context about the problem here.
