---
name: Feature request
about: Suggest a new feature or improvement
title: "[FEATURE] "
labels: ["enhancement"]
assignees: []

---

**Describe the feature**
A clear description of what you'd like added.

**Use case**
Why is this important / who would use it?

**Additional context**
Sketches, mockups, or links welcome.
