// app/proof/rankings/page.tsx
// UNLISTED reference page: which domains we own actually rank on Google, from real Search Console
// data. Built for two audiences — a rep on a cold call, and the prospect they send it to.
//
// ⚠️ THE SPLIT IS CITY+TRADE vs GENERIC, AND IT IS NOT THE SPLIT I FIRST BUILT. The first cut
// called "grafton towing" a BRANDED query and discounted it as near-tautological — on the
// assumption that a business called Grafton Towing exists and people were searching its name.
// It does not exist. These are keyword domains with generated sites; nobody is searching a brand.
// So "grafton towing" is a commercial geo query and ranking #1 for it is the thesis working,
// not a circular result. The correction came from Sandon, not from me noticing — I had reasoned
// confidently from an assumption I never checked, which is the §9 failure in miniature.
//
// The honest split is therefore by DIFFICULTY, not brand: city+trade (what the exact-match domain
// is built to win) vs generic/near-me (harder, no geo token to match on).
//
// ⚠️ THE VOLUME IS SMALL AND THE PAGE SAYS SO. 20 clicks / 1,536 impressions across 19 sites in 28
// days. A reference page that showed the positions without the volume would be selling a number
// that cannot survive the first follow-up question.
//
// ⚠️ Data is a DATED SNAPSHOT (lib/proof/rankingSnapshot.json), regenerated by
// `node scripts/gsc-rank-report.mjs --json`. The date is rendered prominently on purpose: a
// number in a file never disagrees with itself, so the only defence against staleness is showing
// when it was measured (CLAUDE.md §4).
import type { Metadata } from 'next';
import Link from 'next/link';
import SiteHeader from '@/components/site/site-header';
import RankDotPlot from '@/components/charts/rank-dot-plot';
import snapshot from '@/lib/proof/rankingSnapshot.json';

export const metadata: Metadata = {
  title: 'What our domains rank for — QuickSites',
  description: 'Real Search Console data for the domains we own and operate.',
  robots: { index: false, follow: false },
};

type Q = { query: string; clicks: number; impressions: number; position: number; kind: string };
type Site = {
  host: string;
  clicks: number;
  impressions: number;
  position: number | null;
  queries: Q[];
};

const sites = snapshot.sites as Site[];
// ⚠️ quicksites.ai is excluded throughout — our own brand ranking for its own name proves
// nothing about whether a geo domain wins commercial searches.
const geoSites = sites.filter((s) => !s.host.includes('quicksites'));
const pageOne = geoSites.flatMap((s) =>
  s.queries.filter((q) => q.position <= 10).map((q) => ({ ...q, host: s.host }))
);
const cityTrade = pageOne
  .filter((q) => q.kind === 'city_trade')
  .sort((a, b) => a.position - b.position);
const generic = pageOne.filter((q) => q.kind === 'generic').sort((a, b) => a.position - b.position);
const totalClicks = geoSites.reduce((n, s) => n + s.clicks, 0);
const totalImpr = geoSites.reduce((n, s) => n + s.impressions, 0);

function Stat({ n, label, sub }: { n: string; label: string; sub?: string }) {
  return (
    <div className="rounded-xl border border-zinc-800 bg-zinc-900/40 p-4">
      <div className="text-2xl font-bold text-white">{n}</div>
      <div className="mt-0.5 text-xs font-medium uppercase tracking-wide text-zinc-500">
        {label}
      </div>
      {sub && <div className="mt-1 text-xs text-zinc-600">{sub}</div>}
    </div>
  );
}

export default function RankingsProofPage() {
  return (
    <>
      <SiteHeader sticky />
      <div className="min-h-screen bg-zinc-950 text-white">
        <section className="mx-auto max-w-3xl px-6 pb-8 pt-16">
          <div className="flex flex-wrap gap-2">
            <span className="rounded-full border border-zinc-700 bg-zinc-900 px-3 py-1 text-xs font-medium text-zinc-400">
              Reference — unlisted
            </span>
            <span className="rounded-full border border-emerald-500/40 bg-emerald-500/10 px-3 py-1 text-xs font-medium text-emerald-300">
              Google Search Console · measured {snapshot.measuredAt}
            </span>
          </div>
          <h1 className="mt-6 text-4xl font-extrabold tracking-tight">
            What our domains actually rank for
          </h1>
          <p className="mt-4 text-lg leading-relaxed text-zinc-400">
            Straight out of Google Search Console for domains we own and run — no estimates, no
            third-party rank tracker. Window: {snapshot.window.start} to {snapshot.window.end}.
          </p>

          <div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4">
            <Stat n={String(geoSites.length)} label="live domains" sub="with GSC history" />
            <Stat n={String(pageOne.length)} label="page-one queries" sub="position ≤ 10" />
            <Stat n={totalImpr.toLocaleString()} label="impressions" sub="28 days" />
            <Stat n={String(totalClicks)} label="clicks" sub="28 days" />
          </div>
        </section>

        <section className="mx-auto max-w-3xl px-6 pb-6">
          <h2 className="text-sm font-semibold uppercase tracking-wider text-zinc-500">
            The {pageOne.length} queries on page one
          </h2>
          {/* ⚠️ One chart instead of the two lists this replaced. The lists said the same thing
              twice and separated the flattering half from the sobering one; here position and
              volume sit on the same row, so a reader cannot take one without the other. */}
          <RankDotPlot queries={pageOne} />
          <div className="mt-3 grid gap-3 sm:grid-cols-2">
            <p className="text-xs leading-relaxed text-zinc-500">
              <span className="font-semibold text-zinc-300">City + trade</span> is the exact search
              someone types when they need this service in this town — the whole thesis of an
              exact-match domain, and the easiest kind for one to win.
            </p>
            <p className="text-xs leading-relaxed text-zinc-500">
              <span className="font-semibold text-zinc-300">Generic &ldquo;near me&rdquo;</span> is
              harder — no city or trade token to match on. ⚠️ Read those with suspicion: each was
              seen once or twice in 28 days and produced zero clicks. A #6 on a query that surfaced
              once is close to noise.
            </p>
          </div>
        </section>

        <section className="mx-auto max-w-3xl px-6 pb-6">
          <div className="rounded-xl border border-amber-500/30 bg-amber-500/[0.06] p-5">
            <h2 className="text-base font-semibold text-white">
              What this proves — and what it doesn&apos;t
            </h2>
            <div className="mt-3 space-y-3 text-sm leading-relaxed text-zinc-300">
              <p>
                <span className="font-semibold text-emerald-300">It proves</span> these are real,
                indexed domains with a year of Google history, and that an exact-match
                city-and-trade name does reach page one for the search it was bought for. That is
                the mechanism working, at small scale.
              </p>
              <p>
                <span className="font-semibold text-amber-300">It does not prove volume.</span> The
                whole portfolio drew {totalClicks} clicks in 28 days, and all of them came from the
                city-and-trade group (top queries: 62, 29 and 16 impressions). The generic
                &ldquo;near me&rdquo; rankings drew{' '}
                <strong className="text-zinc-200">no clicks at all</strong> on 1–2 impressions each.
                These are small towns and narrow searches — a real asset, not a firehose.
              </p>
              <p>
                <span className="font-semibold text-amber-300">
                  It says nothing about a new domain.
                </span>{' '}
                These sites have been live for about a year. A domain that goes up today has no
                history and will not rank for months, if it ever does. Anyone quoting these numbers
                for a brand-new name is quoting the wrong page.
              </p>
            </div>
          </div>
        </section>

        <section className="mx-auto max-w-3xl px-6 pb-24">
          <h2 className="text-sm font-semibold uppercase tracking-wider text-zinc-500">
            Every connected domain
          </h2>
          <div className="mt-3 overflow-x-auto rounded-xl border border-zinc-800">
            <table className="w-full text-sm">
              <thead className="bg-zinc-900/60 text-xs uppercase tracking-wide text-zinc-500">
                <tr>
                  <th className="px-4 py-2 text-left font-medium">Domain</th>
                  <th className="px-4 py-2 text-right font-medium">Impressions</th>
                  <th className="px-4 py-2 text-right font-medium">Clicks</th>
                  <th className="px-4 py-2 text-right font-medium">Avg position</th>
                </tr>
              </thead>
              <tbody>
                {geoSites.map((s) => (
                  <tr key={s.host} className="border-t border-zinc-800/70">
                    <td className="px-4 py-2 font-mono text-xs text-zinc-300">{s.host}</td>
                    <td className="px-4 py-2 text-right font-mono text-xs text-zinc-400">
                      {s.impressions.toLocaleString()}
                    </td>
                    <td className="px-4 py-2 text-right font-mono text-xs text-zinc-400">
                      {s.clicks}
                    </td>
                    <td className="px-4 py-2 text-right font-mono text-xs text-zinc-500">
                      {s.position ?? '—'}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <p className="mt-4 text-xs leading-relaxed text-zinc-600">
            Snapshot taken {snapshot.measuredAt} via Google Search Console. Regenerate with{' '}
            <code className="rounded bg-zinc-900 px-1">
              node scripts/gsc-rank-report.mjs --json
            </code>
            . Average position is across every query a domain surfaced for, so a site ranking #1 for
            its name and #60 for everything else shows a middling average — the per-query rows above
            are the meaningful view.{' '}
            <Link href="/for-sales" className="text-amber-400 underline underline-offset-4">
              ← back
            </Link>
          </p>
        </section>
      </div>
    </>
  );
}
