// app/page.tsx — server component: SSRs the showcase data so the "Built with
// QuickSites" row is in the initial HTML for everyone (incl. unauthenticated
// users), independent of any client fetch/cache. The rest of the homepage is the
// client component HomeClient.

import type { Metadata } from 'next';
import HomeClient from '@/components/home/home-client';
import SiteShowcase from '@/components/home/site-showcase';
import { getShowcaseData } from '@/lib/home/getShowcaseData';

export const dynamic = 'force-dynamic';

// Homepage-scoped share metadata. Kept on the page (not the org-aware root
// layout) so it only brands "/" — other routes keep their own OG. The image is
// generated by app/api/og/home; `metadataBase` resolves the relative path to an
// absolute URL for crawlers.
const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || 'https://quicksites.ai';
const OG_TITLE = 'QuickSites — One-Click Local Websites';
const OG_DESCRIPTION =
  'Launch a professional site for your local business in minutes — AI-assisted, with built-in commerce and a partner program.';

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: OG_TITLE,
  description: OG_DESCRIPTION,
  alternates: { canonical: '/' },
  openGraph: {
    type: 'website',
    url: '/',
    siteName: 'QuickSites',
    title: OG_TITLE,
    description: OG_DESCRIPTION,
    images: [{ url: '/api/og/home', width: 1200, height: 630, alt: 'QuickSites — One-Click Local Websites' }],
  },
  twitter: {
    card: 'summary_large_image',
    title: OG_TITLE,
    description: OG_DESCRIPTION,
    images: ['/api/og/home'],
  },
};

export default async function Page() {
  let initial;
  try {
    const data = await getShowcaseData();
    // SSR payload is the public view — drop admin-hidden sites. Admins still get
    // the full set (incl. hidden, for management) via the client revalidation fetch.
    const visible = data.sites.filter((s) => !s.hidden);
    // Only seed the client with SSR data when we actually have sites. If the query
    // hiccuped and returned empty, passing a truthy-but-empty object would make the
    // client treat it as "loaded, just empty" and render nothing — skipping the
    // localStorage cache + /api/public/showcase fallback. Passing undefined lets the
    // client paint from cache (returning visitors) and revalidate, so a transient
    // SSR miss never blanks the row.
    initial = visible.length > 0 ? { ...data, sites: visible } : undefined;
  } catch {
    initial = undefined; // client component will fetch/cache as a fallback
  }
  return <HomeClient showcase={<SiteShowcase initialData={initial} />} />;
}
