/**
 * @jest-environment node
 */
// lib/sites/__tests__/siteProgress.test.ts
//
// "Where did they leave off?" — one pure function the owner's new-site email and the Sites
// column on /admin/users both read, so the inbox and the page cannot disagree.
import fs from 'node:fs';
import path from 'node:path';
import { analyzeSiteProgress, testTrafficReason, blockTypesOf } from '@/lib/sites/siteProgress';
import { DEMO_RECORDER_BUSINESS_NAMES } from '@/lib/demos/recorderIdentity';

const read = (p: string) => fs.readFileSync(path.join(process.cwd(), p), 'utf8');
const strip = (s: string) => s.replace(/\/\/[^\n]*/g, '').replace(/\/\*[\s\S]*?\*\//g, '').replace(/\{\/\*[\s\S]*?\*\/\}/g, '');

const T0 = '2026-10-05T18:00:00.000Z';
const base = { created_at: T0, published: false, save_count: 0 };

describe('analyzeSiteProgress — the two axes', () => {
  it('the typical guest build: generated by AI, no edits, saw the prompt, never opened it', () => {
    const p = analyzeSiteProgress({
      template: { ...base, updated_at: '2026-10-05T18:02:00.000Z' },
      versions: 0,
      aiCalls: 5,
      lastAiAt: '2026-10-05T18:01:30.000Z',
      funnel: [{ event: 'prompt_shown', created_at: '2026-10-05T18:02:10.000Z' }],
      user: { is_anonymous: true },
    });
    expect(p.work).toBe('generated');
    expect(p.signup).toBe('prompted');
    expect(p.summary).toBe('Built with AI (5 calls), no edits saved; saw the sign-up prompt, never opened it. Last activity 2 min after creation.');
    expect(p.nextStep).toMatch(/No email on record/);
  });

  it('edits count from save_count OR versions, and the sign-up axis climbs to its highest event', () => {
    const p = analyzeSiteProgress({
      template: { ...base, save_count: 3 },
      funnel: [
        { event: 'prompt_shown', created_at: T0 },
        { event: 'signup_opened', created_at: T0 },
        { event: 'signup_submitted', created_at: T0 },
        { event: 'signup_email_sent', created_at: '2026-10-05T18:20:00.000Z' },
      ],
      user: { is_anonymous: true },
    });
    expect(p.work).toBe('edited');
    expect(p.signup).toBe('email_sent');
    expect(p.summary).toMatch(/^Saved 3 edits; sign-up email sent, not confirmed/);
    expect(p.nextStep).toMatch(/deliverability/);
    expect(p.minutesActive).toBe(20);
  });

  it('a real account outranks every funnel event, and published outranks everything', () => {
    const acct = analyzeSiteProgress({ template: { ...base, save_count: 1 }, user: { is_anonymous: false, email: 'a@b.co' } });
    expect(acct.signup).toBe('account');
    expect(acct.nextStep).toMatch(/ready to go live/);
    const live = analyzeSiteProgress({ template: { ...base, published: true }, user: { is_anonymous: false } });
    expect(live.work).toBe('published');
    expect(live.nextStep).toBe('Live. Nothing to do.');
  });

  it('with AI calls unknown (the users list), says only what it can see', () => {
    const p = analyzeSiteProgress({ template: base, user: { is_anonymous: true } });
    expect(p.summary).toMatch(/^No edits saved; never saw a sign-up prompt\./);
    expect(p.summary).not.toMatch(/nothing generated/);
  });

  it('reads block types from either array shape and tolerates garbage', () => {
    expect(blockTypesOf({ pages: [{ blocks: [{ type: 'hero' }, { type: 'services' }] }] })).toEqual({ pages: 1, blocks: ['hero', 'services'] });
    expect(blockTypesOf({ pages: [{ content_blocks: [{ type: 'hero' }] }, {}] })).toEqual({ pages: 2, blocks: ['hero'] });
    expect(blockTypesOf(null)).toEqual({ pages: 0, blocks: [] });
    expect(blockTypesOf('nope')).toEqual({ pages: 0, blocks: [] });
  });
});

describe('testTrafficReason — the owner is never emailed about himself', () => {
  const adminEmails = ['sandonjurowski@gmail.com'];
  it('an operator account', () => {
    expect(testTrafficReason({ isAdminUser: true, adminEmails })).toBe('operator');
  });
  it("the owner's +alias test accounts", () => {
    expect(testTrafficReason({ userEmail: 'sandonjurowski+tester2@gmail.com', adminEmails })).toBe('owner_test_account');
    expect(testTrafficReason({ userEmail: 'SandonJurowski+x@Gmail.com', adminEmails })).toBe('owner_test_account');
  });
  it('the demo recorder, by the name it types', () => {
    for (const n of DEMO_RECORDER_BUSINESS_NAMES) expect(testTrafficReason({ businessName: n, adminEmails })).toBe('demo_recorder');
  });
  it('a stranger is a stranger', () => {
    expect(testTrafficReason({ businessName: 'Minus the Runaround', userEmail: null, adminEmails })).toBeNull();
    expect(testTrafficReason({ userEmail: 'someone@gmail.com', adminEmails })).toBeNull();
    expect(testTrafficReason({ userEmail: 'sandonjurowski@other.com', adminEmails })).toBeNull();
  });
});

// ⚠️ SOURCE GUARDS — the defects these catch are invisible to unit tests of the pure function.
describe('the recorder and the alert share one name list', () => {
  it('record-demo types the shared constant, never a literal', () => {
    const src = strip(read('scripts/record-demo.mts'));
    expect(src).toMatch(/DEMO_RECORDER_BUSINESS_NAMES\[0\]/);
    expect(src).not.toMatch(/typeSlowly\([^)]*"Wildflower Candle Co\."/);
  });
});

describe('the cron', () => {
  const src = strip(read('app/api/cron/site-created-alert/route.ts'));
  it('marks AFTER the send resolves, and records test traffic instead of emailing it', () => {
    const sendAt = src.indexOf('await sendEmail(');
    const markAt = src.indexOf("alerted_at: new Date().toISOString()");
    expect(sendAt).toBeGreaterThan(0);
    expect(markAt).toBeGreaterThan(sendAt);
    expect(src).toMatch(/skipped_reason: report\.testTraffic/);
  });
  it('never updates templates directly (the guard trigger would reject it anyway)', () => {
    expect(src).not.toMatch(/from\('templates'\)\s*\.update/);
  });
  it('waits for the site to settle and ignores our own pipelines', () => {
    expect(src).toMatch(/SETTLE_MINUTES/);
    for (const s of ['listing_import', 'demo_seed', 'directory', 'operator_draft', 'persona_build']) expect(src).toContain(`'${s}'`);
  });
  it('is scheduled', () => {
    const v = JSON.parse(read('vercel.json'));
    expect(v.crons.some((c: any) => c.path === '/api/cron/site-created-alert')).toBe(true);
  });
});

describe('both surfaces read the one analysis', () => {
  it('the email and the users list both call analyzeSiteProgress', () => {
    expect(strip(read('lib/sites/siteProgressServer.ts'))).toMatch(/analyzeSiteProgress\(/);
    expect(strip(read('app/api/admin/users/list/route.ts'))).toMatch(/analyzeSiteProgress\(/);
    expect(strip(read('components/admin/users/users-plans-manager.tsx'))).toMatch(/s\.left_off/);
  });
});
