/**
 * scripts/build-resume.ts — one Markdown résumé in, three artifacts out.
 *
 *   npx tsx --env-file=.env.local scripts/build-resume.ts <resume.md> [--slug s] [--upload] [--template <id>]
 *
 * ⚠️ WHY THIS EXISTS. The three downloadable copies on a hosted résumé — .md, .pdf, .docx — were
 * generated by hand, once. So a one-word correction meant three separate edits, and the artifact
 * hardest to edit (the PDF, whose text is subsetted glyph IDs rather than characters) was the one
 * most likely to be skipped. Three copies of a fact, maintained independently, disagree eventually;
 * that is the same defect as the site whose block list is stored twice, exported to a filesystem.
 * The Markdown is the source. The other two are outputs, and are never edited.
 *
 * ⚠️ IT IS DELIBERATELY DUMB ABOUT CONTENT. It converts; it does not improve, summarise or
 * reformat prose. A résumé is a factual claim about someone's employment, and the rule that governs
 * `lib/rebuild/importResume.ts` governs here too: rearranging text a person wrote is fine, adding
 * to it is not. Nothing in this file calls a model.
 *
 * This is the mechanism behind Verbatim's "a PDF, not just a web page" — same source, same rule.
 */

import fs from 'node:fs';
import path from 'node:path';
import { marked } from 'marked';

const PAGE_CSS = `
  @page { size: Letter; margin: 0.6in 0.7in; }
  * { box-sizing: border-box; }
  body { font: 10.5pt/1.45 "Helvetica Neue", Helvetica, Arial, sans-serif; color: #111; margin: 0; }
  h1 { font-size: 21pt; margin: 0 0 2pt; letter-spacing: -0.01em; }
  h1 + p { color: #444; font-size: 9.5pt; margin: 0 0 12pt; }
  h2 { font-size: 10.5pt; text-transform: uppercase; letter-spacing: .09em; color: #333;
       border-bottom: .75pt solid #bbb; padding-bottom: 2pt; margin: 15pt 0 6pt; }
  h3 { font-size: 11pt; margin: 10pt 0 3pt; }
  p  { margin: 0 0 7pt; }
  ul { margin: 0 0 8pt; padding-left: 15pt; }
  li { margin-bottom: 3pt; }
  a  { color: #111; text-decoration: none; }
  /* Never split a role's heading from its first bullet across a page break. */
  h2, h3 { break-after: avoid; page-break-after: avoid; }
  li { break-inside: avoid; page-break-inside: avoid; }
`;

export function resumeHtml(md: string, title: string): string {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8">
<title>${title}</title><style>${PAGE_CSS}</style></head>
<body>${marked.parse(md, { async: false }) as string}</body></html>`;
}

/** Markdown → the plain paragraph/heading/bullet stream `docx` needs. No styling opinions. */
async function buildDocx(md: string) {
  const { Document, Packer, Paragraph, HeadingLevel, TextRun } = await import('docx');
  const children: any[] = [];

  for (const raw of md.split('\n')) {
    const line = raw.trimEnd();
    if (!line.trim()) continue;

    const h = /^(#{1,4})\s+(.*)$/.exec(line);
    if (h) {
      const level = h[1].length;
      children.push(
        new Paragraph({
          text: stripInline(h[2]),
          heading:
            level === 1
              ? HeadingLevel.TITLE
              : level === 2
                ? HeadingLevel.HEADING_1
                : HeadingLevel.HEADING_2,
          spacing: { before: level === 1 ? 0 : 200, after: 100 },
        }),
      );
      continue;
    }

    const b = /^[-*]\s+(.*)$/.exec(line);
    if (b) {
      children.push(
        new Paragraph({ text: stripInline(b[1]), bullet: { level: 0 }, spacing: { after: 60 } }),
      );
      continue;
    }

    children.push(
      new Paragraph({ children: [new TextRun(stripInline(line))], spacing: { after: 120 } }),
    );
  }

  return Packer.toBuffer(new Document({ sections: [{ children }] }));
}

/** Drop Markdown emphasis/link syntax, keep the words exactly. */
function stripInline(s: string): string {
  return s
    .replace(/\[([^\]]+)\]\([^)]*\)/g, '$1')
    .replace(/\*\*([^*]+)\*\*/g, '$1')
    .replace(/(^|\W)\*([^*]+)\*/g, '$1$2')
    .replace(/`([^`]+)`/g, '$1');
}

async function buildPdf(html: string): Promise<Buffer> {
  const puppeteer = (await import('puppeteer')).default;
  const browser = await puppeteer.launch({ args: ['--no-sandbox'] });
  try {
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: 'load' });
    return Buffer.from(
      await page.pdf({ format: 'letter', printBackground: true, preferCSSPageSize: true }),
    );
  } finally {
    await browser.close();
  }
}

/** Human size label, matching what the file_downloads block shows. */
export function sizeLabel(bytes: number): string {
  return bytes >= 1024 * 1024
    ? `${(bytes / 1024 / 1024).toFixed(1)} MB`
    : `${Math.round(bytes / 1024)} KB`;
}

/**
 * Re-stamp the download block's size labels from the bytes just uploaded.
 *
 * ⚠️ A STORED SIZE IS A FOURTH COPY OF THE FACT, AND THIS SCRIPT CREATED THE DRIFT IT NOW FIXES.
 * Regenerating the PDF took it from 71 KB to 100 KB while the page went on advertising "71 KB" —
 * the exact defect this script was written to end, reappearing one layer up because the artifacts
 * were regenerated and the label describing them was not. A number about a file belongs to
 * whatever writes the file.
 */
async function restampSizes(templateId: string, files: { name: string; body: Buffer }[]) {
  const { createClient } = await import('@supabase/supabase-js');
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_SECRET_KEY;
  if (!url || !key) throw new Error('Supabase env missing.');
  const s = createClient(url, key, { auth: { persistSession: false } });

  const byName = new Map(files.map((f) => [f.name, f.body.length]));
  // ⚠️ Read `rev` and pass it back. `commit_template` is optimistic-concurrency guarded; a
  // hard-coded base_rev of 0 does not mean "I don't care", it means "I believe this row has never
  // been written", and the RPC correctly answers merge_conflict.
  const { data: row, error } = await s
    .from('templates')
    .select('data, rev')
    .eq('id', templateId)
    .maybeSingle();
  if (error || !row) throw new Error(`template ${templateId} not found`);

  let changed = 0;
  // ⚠️ Both arrays. A page stores its blocks under `content_blocks` AND `blocks`; patching one
  // leaves the other serving the stale number.
  const data: any = row.data;
  for (const page of data?.pages ?? []) {
    for (const arr of [page?.content_blocks, page?.blocks]) {
      for (const b of arr ?? []) {
        if (b?.type !== 'file_downloads') continue;
        for (const f of b.content?.files ?? []) {
          const name = String(f?.href ?? '').split('/').pop() ?? '';
          const bytes = byName.get(name);
          if (!bytes) continue;
          const next = sizeLabel(bytes);
          if (f.size !== next) {
            console.log(`  size ${name}: ${f.size} → ${next}`);
            f.size = next;
            changed++;
          }
        }
      }
    }
  }
  if (!changed) {
    console.log('  sizes already correct');
    return;
  }

  const { commitTemplatePatch } = await import('../lib/templates/commitTemplatePatch');
  const err = await commitTemplatePatch(templateId, Number((row as any).rev ?? 0), { data }, null);
  if (err) throw new Error(`commit failed: ${err}`);
  console.log(`  re-stamped ${changed} size label(s) — REPUBLISH to push it live`);
}

async function upload(slug: string, files: { name: string; body: Buffer; type: string }[]) {
  const { createClient } = await import('@supabase/supabase-js');
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_SECRET_KEY;
  if (!url || !key) throw new Error('Supabase env missing (URL + service-role/secret key).');
  const s = createClient(url, key, { auth: { persistSession: false } });

  for (const f of files) {
    const at = `${slug}/${f.name}`;
    const { error } = await s.storage
      .from('resumes')
      .upload(at, f.body, { contentType: f.type, upsert: true });
    if (error) throw new Error(`upload ${at}: ${error.message}`);
    console.log(`  uploaded resumes/${at} (${f.body.length} bytes)`);
  }
}

async function main() {
  const args = process.argv.slice(2);
  const src = args.find((a) => !a.startsWith('--'));
  if (!src) throw new Error('usage: build-resume.ts <resume.md> [--slug <slug>] [--upload]');

  const slugArg = args.indexOf('--slug');
  const slug = slugArg >= 0 ? args[slugArg + 1] : 'sandon';
  const base = args.includes('--name')
    ? args[args.indexOf('--name') + 1]
    : path.basename(src, '.md');

  const md = fs.readFileSync(src, 'utf8');
  const title = (/^#\s+(.*)$/m.exec(md)?.[1] ?? base).trim();

  const html = resumeHtml(md, title);
  const [pdf, docx] = await Promise.all([buildPdf(html), buildDocx(md)]);

  const outDir = path.dirname(src);
  const files = [
    { name: `${base}.md`, body: Buffer.from(md, 'utf8'), type: 'text/markdown' },
    { name: `${base}.pdf`, body: pdf, type: 'application/pdf' },
    {
      name: `${base}.docx`,
      body: docx,
      type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    },
  ];
  for (const f of files) fs.writeFileSync(path.join(outDir, f.name), f.body);
  console.log(`built ${files.map((f) => `${f.name} (${f.body.length}B)`).join(', ')}`);

  if (args.includes('--upload')) {
    await upload(slug, files);
    const ti = args.indexOf('--template');
    if (ti >= 0 && args[ti + 1]) await restampSizes(args[ti + 1], files);
    else console.log('  (pass --template <id> to re-stamp the page\'s size labels too)');
  } else {
    console.log('(dry run — pass --upload to publish to Supabase storage)');
  }
}

main().catch((e) => {
  console.error(e instanceof Error ? e.message : e);
  process.exit(1);
});
