name: Deploy Storybook Preview

on:
  pull_request:
    branches: [main]

jobs:
  deploy-storybook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Storybook
        run: npm run build-storybook

      - name: Deploy Storybook to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_STORYBOOK_PROJECT_ID }}
          working-directory: storybook-static
          vercel-args: '--prebuilt'
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
