name: Slack Deploy Notification

on:
  workflow_run:
    workflows: [Release]
    types:
      - completed

jobs:
  notify:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Post to Slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "🚀 quicksites-v2 deployed to production\nBranch: main\nCommit: ${{ github.sha }}\nTime: ${{ github.event.workflow_run.updated_at }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
