name: Sync Issues and PRs to GitHub Project

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

permissions:
  issues: write
  pull-requests: write
  contents: read

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/Silver-Lamp/projects/1
          github-token: ${{ secrets.GITHUB_TOKEN }}
